GET http://localhost:8888/api/tasks
Accept: application/json
###
GET http://localhost:8888/api/tasks/1
Accept: application/json
###
POST http://localhost:8888/api/tasks
Content-Type: application/json

{
  "title":"Zadnie testowe",
  "description":"Tutaj długi opis zadania testowego"
}
###
GET http://localhost:8888/api/tasks/1/attachments
###
POST http://localhost:8888/api/tasks/1/attachments
Content-Type: multipart/form-data; boundary=Tasker

--Tasker
Content-Disposition: form-data; name="file"; filename="testfile.txt"

< C:\Java\Projects\tasker\testfile.txt
--Tasker
###
GET http://localhost:8888/api/tasks/2/attachments/cebb5c08-3dba-4352-b670-eb5b94fe45ef
###
PUT http://localhost:8888/api/tasks/1
Content-Type: application/json

{
  "title":"Zmiana",
  "description":"Opis"
}
###
DELETE http://localhost:8888/api/tasks/1
###